name: ScalaEureka workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build JAR
        run: sbt package
      - name: Run unit tests
        run: sbt clean test
      - name: Publish
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_VERSION: ${{ github.event.release.tag_name }}
      - name: Add JAR to release
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/eureka-${{ github.event.release.tag_name }}.jar
          asset_name: ${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive
