name: ScalaEureka workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  scala:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: sbt clean test
      - name: Publish
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_VERSION: ${{ github.ref }}
